name: Build Android APK

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk wget
        sudo apt-get install -y python3-pip autoconf libtool pkg-config
        sudo apt-get install -y zlib1g-dev libncurses5-dev libncursesw5-dev
        sudo apt-get install -y libtinfo6 cmake libffi-dev libssl-dev
    
    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer==1.5.0
        pip install cython==0.29.33
    
    - name: Create buildozer.spec if not exists
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
    
    - name: Build APK with Buildozer
      run: |
        yes | buildozer android debug
      env:
        ANDROIDSDK: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
        ANDROIDNDK: ${{ github.workspace }}/.buildozer/android/platform/android-ndk
        ANDROIDAPI: 31
        ANDROIDMINAPI: 21
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-apk
        path: bin/*.apk
        retention-days: 30
    
    - name: Create Release (optional)
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0-${{ github.run_number }}
        name: Snake Game v1.0 Build ${{ github.run_number }}
        files: bin/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
