name: CodeFactor

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CodeFactor Analysis
        uses: codefactor-io/codefactor-action@v1
        with:
          fail_on_white_issues: true
          repo: ${{ github.repository }}
          oauth_token: ${{ secrets.CODEFACTOR_TOKEN }}
